global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus-service-demo'
    metrics_path: /metrics
    static_configs:
      - targets:
          - prometheus-service-demo-0:8080
          - prometheus-service-demo-1:8080
          - prometheus-service-demo-2:8080

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
